### PR TITLE
Manual trigger fix

### PR DESCRIPTION
**Pull request by luciipak**

### CODE REVIEW

**Comment by luciipak** [comment]
Removed `orDev` handling because when a user updates selected NI device, it writes to the config file and will be used by default next time. Additionally, it will create new analogue and digital output channels regardless each time a new device is selected

**Comment by luciipak** [comment]
https://github.com/CuriBio/nautilus_acquisition/assets/84344924/1bc1690c-0631-4c59-bf8c-9b66791bf726

**Comment by jperson** [comment]
This needs to bump the patch version

**Review by jperson — CHANGES_REQUESTED** [review]
see slack thread, this change breaks the sw

**Comment by jperson** [comment]
Looks good, one thing, can you add a call to QString::trimmed on the device name so the second device doesn't start with a leading space

Screenshot 2024-01-05 at 8 16 17 AM

**Review by jperson — APPROVED** [review]

**Pull request merged**
